### PR TITLE
Refactor Backup Enum

### PR DESCRIPTION
**Pull request by slobberbone**

### CODE REVIEW

**Comment by vinceg77** [comment]
@TesteursFous : Il suffit de faire un restore de backup et de valider qu'il fonctionne

**Review by vinceg77 — COMMENTED** [review]
Beaucoup d'erreurs (certaines présentes dans mes restore sur d'autres versions nextdom) d'autres semblent spécifiques à ce commit  : PHP Warning:  Use of undefined constant NEXTDOM_ROOT_FOLDER

Mais à la fin mes données sont bien la quand meme ....


> [ Restore Backup Process ]
*************** starting restore procedure at 2019-12-09 15:10:31 ***************
...file used for restoration: /var/lib/nextdom/backup/backup-MaisonChelles-3.3.38-2019-12-09-05h51.tar.gz
OK
stopping Nextdom system......  OK
extracting backup archive......  OK
restoring plugins......  OK
restoring mysql database......  OK
importing Jeedom configuration......  OK
restoring custom data...
... PHP Warning:  Use of undefined constant NEXTDOM_ROOT_FOLDERS - assumed 'NEXTDOM_ROOT_FOLDERS' (this will throw an Error in a future version of PHP) in /var/www/html/src/Managers/BackupManager.php on line 760
PHP Warning:  in_array() expects parameter 2 to be array, string given in /var/www/html/src/Managers/BackupManager.php on line 760
PHP Warning:  Use of undefined constant NEXTDOM_ROOT_FILES - assumed 'NEXTDOM_ROOT_FILES' (this will throw an Error in a future version of PHP) in /var/www/html/src/Managers/BackupManager.php on line 761
PHP Warning:  in_array() expects parameter 2 to be array, string given in /var/www/html/src/Managers/BackupManager.php on line 761
PHP Warning:  Use of undefined constant JEEDOM_BACKUP_FOLDERS - assumed 'JEEDOM_BACKUP_FOLDERS' (this will throw an Error in a future version of PHP) in /var/www/html/src/Managers/BackupManager.php on line 762
PHP Warning:  in_array() expects parameter 2 to be array, string given in /var/www/html/src/Managers/BackupManager.php on line 762
PHP Warning:  Use of undefined constant JEEDOM_BACKUP_FILES - assumed 'JEEDOM_BACKUP_FILES' (this will throw an Error in a future version of PHP) in /var/www/html/src/Managers/BackupManager.php on line 763
PHP Warning:  in_array() expects parameter 2 to be array, string given in /var/www/html/src/Managers/BackupManager.php on line 763
...Restoring folder: 3rdparty
OK
PHP Warning:  Use of undefined constant NEXTDOM_ROOT_FOLDERS - assumed 'NEXTDOM_ROOT_FOLDERS' (this will throw an Error in a future version of PHP) in /var/www/html/src/Managers/BackupManager.php on line 760
PHP Warning:  in_array() expects parameter 2 to be array, string given in /var/www/html/src/Managers/BackupManager.php on line 760
PHP Warning:  Use of undefined constant NEXTDOM_ROOT_FILES - assumed 'NEXTDOM_ROOT_FILES' (this will throw an Error in a future version of PHP) in /var/www/html/src/Managers/BackupManager.php on line 761
PHP Warning:  in_array() expects parameter 2 to be array, string given in /var/www/html/src/Managers/BackupManager.php on line 761
PHP Warning:  Use of undefined constant JEEDOM_BACKUP_FOLDERS - assumed 'JEEDOM_BACKUP_FOLDERS' (this will throw an Error in a future version of PHP) in /var/www/html/src/Managers/BackupManager.php on line 762
PHP Warning:  in_array() expects parameter 2 to be array, string given in /var/www/html/src/Managers/BackupManager.php on line 762
PHP Warning:  Use of undefined constant JEEDOM_BACKUP_FILES - assumed 'JEEDOM_BACKUP_FILES' (this will throw an Error in a future version of PHP) in /var/www/html/src/Managers/BackupManager.php on line 763
PHP Warning:  in_array() expects parameter 2 to be array, string given in /var/www/html/src/Managers/BackupManager.php on line 763
...Restoring folder: @LongLink
OK
PHP Warning:  Use of undefined constant NEXTDOM_ROOT_FOLDERS - assumed 'NEXTDOM_ROOT_FOLDERS' (this will throw an Error in a future version of PHP) in /var/www/html/src/Managers/BackupManager.php on line 760
PHP Warning:  in_array() expects parameter 2 to be array, string given in /var/www/html/src/Managers/BackupManager.php on line 760
PHP Warning:  Use of undefined constant NEXTDOM_ROOT_FILES - assumed 'NEXTDOM_ROOT_FILES' (this will throw an Error in a future version of PHP) in /var/www/html/src/Managers/BackupManager.php on line 761
PHP Warning:  in_array() expects parameter 2 to be array, string given in /var/www/html/src/Managers/BackupManager.php on line 761
PHP Warning:  Use of undefined constant JEEDOM_BACKUP_FOLDERS - assumed 'JEEDOM_BACKUP_FOLDERS' (this will throw an Error in a future version of PHP) in /var/www/html/src/Managers/BackupManager.php on line 762
PHP Warning:  in_array() expects parameter 2 to be array, string given in /var/www/html/src/Managers/BackupManager.php on line 762
PHP Warning:  Use of undefined constant JEEDOM_BACKUP_FILES - assumed 'JEEDOM_BACKUP_FILES' (this will throw an Error in a future version of PHP) in /var/www/html/src/Managers/BackupManager.php on line 763
PHP Warning:  in_array() expects parameter 2 to be array, string given in /var/www/html/src/Managers/BackupManager.php on line 763
...Restoring folder: core
OK
PHP Warning:  Use of undefined constant NEXTDOM_ROOT_FOLDERS - assumed 'NEXTDOM_ROOT_FOLDERS' (this will throw an Error in a future version of PHP) in /var/www/html/src/Managers/BackupManager.php on line 760
PHP Warning:  in_array() expects parameter 2 to be array, string given in /var/www/html/src/Managers/BackupManager.php on line 760
PHP Warning:  Use of undefined constant NEXTDOM_ROOT_FILES - assumed 'NEXTDOM_ROOT_FILES' (this will throw an Error in a future version of PHP) in /var/www/html/src/Managers/BackupManager.php on line 761
PHP Warning:  in_array() expects parameter 2 to be array, string given in /var/www/html/src/Managers/BackupManager.php on line 761
PHP Warning:  Use of undefined constant JEEDOM_BACKUP_FOLDERS - assumed 'JEEDOM_BACKUP_FOLDERS' (this will throw an Error in a future version of PHP) in /var/www/html/src/Managers/BackupManager.php on line 762
PHP Warning:  in_array() expects parameter 2 to be array, string given in /var/www/html/src/Managers/BackupManager.php on line 762
PHP Warning:  Use of undefined constant JEEDOM_BACKUP_FILES - assumed 'JEEDOM_BACKUP_FILES' (this will throw an Error in a future version of PHP) in /var/www/html/src/Managers/BackupManager.php on line 763
PHP Warning:  in_array() expects parameter 2 to be array, string given in /var/www/html/src/Managers/BackupManager.php on line 763
...Restoring folder: data
OK
PHP Warning:  Use of undefined constant NEXTDOM_ROOT_FOLDERS - assumed 'NEXTDOM_ROOT_FOLDERS' (this will throw an Error in a future version of PHP) in /var/www/html/src/Managers/BackupManager.php on line 760
PHP Warning:  in_array() expects parameter 2 to be array, string given in /var/www/html/src/Managers/BackupManager.php on line 760
PHP Warning:  Use of undefined constant NEXTDOM_ROOT_FILES - assumed 'NEXTDOM_ROOT_FILES' (this will throw an Error in a future version of PHP) in /var/www/html/src/Managers/BackupManager.php on line 761
PHP Warning:  in_array() expects parameter 2 to be array, string given in /var/www/html/src/Managers/BackupManager.php on line 761
PHP Warning:  Use of undefined constant JEEDOM_BACKUP_FOLDERS - assumed 'JEEDOM_BACKUP_FOLDERS' (this will throw an Error in a future version of PHP) in /var/www/html/src/Managers/BackupManager.php on line 762
PHP Warning:  in_array() expects parameter 2 to be array, string given in /var/www/html/src/Managers/BackupManager.php on line 762
PHP Warning:  Use of undefined constant JEEDOM_BACKUP_FILES - assumed 'JEEDOM_BACKUP_FILES' (this will throw an Error in a future version of PHP) in /var/www/html/src/Managers/BackupManager.php on line 763
PHP Warning:  in_array() expects parameter 2 to be array, string given in /var/www/html/src/Managers/BackupManager.php on line 763
...Restoring folder: desktop
OK
PHP Warning:  Use of undefined constant NEXTDOM_ROOT_FOLDERS - assumed 'NEXTDOM_ROOT_FOLDERS' (this will throw an Error in a future version of PHP) in /var/www/html/src/Managers/BackupManager.php on line 760
PHP Warning:  in_array() expects parameter 2 to be array, string given in /var/www/html/src/Managers/BackupManager.php on line 760
PHP Warning:  Use of undefined constant NEXTDOM_ROOT_FILES - assumed 'NEXTDOM_ROOT_FILES' (this will throw an Error in a future version of PHP) in /var/www/html/src/Managers/BackupManager.php on line 761
PHP Warning:  in_array() expects parameter 2 to be array, string given in /var/www/html/src/Managers/BackupManager.php on line 761
PHP Warning:  Use of undefined constant JEEDOM_BACKUP_FOLDERS - assumed 'JEEDOM_BACKUP_FOLDERS' (this will throw an Error in a future version of PHP) in /var/www/html/src/Managers/BackupManager.php on line 762
PHP Warning:  in_array() expects parameter 2 to be array, string given in /var/www/html/src/Managers/BackupManager.php on line 762
PHP Warning:  Use of undefined constant JEEDOM_BACKUP_FILES - assumed 'JEEDOM_BACKUP_FILES' (this will throw an Error in a future version of PHP) in /var/www/html/src/Managers/BackupManager.php on line 763
PHP Warning:  in_array() expects parameter 2 to be array, string given in /var/www/html/src/Managers/BackupManager.php on line 763
...Restoring folder: install
OK
PHP Warning:  Use of undefined constant NEXTDOM_ROOT_FOLDERS - assumed 'NEXTDOM_ROOT_FOLDERS' (this will throw an Error in a future version of PHP) in /var/www/html/src/Managers/BackupManager.php on line 760
PHP Warning:  in_array() expects parameter 2 to be array, string given in /var/www/html/src/Managers/BackupManager.php on line 760
PHP Warning:  Use of undefined constant NEXTDOM_ROOT_FILES - assumed 'NEXTDOM_ROOT_FILES' (this will throw an Error in a future version of PHP) in /var/www/html/src/Managers/BackupManager.php on line 761
PHP Warning:  in_array() expects parameter 2 to be array, string given in /var/www/html/src/Managers/BackupManager.php on line 761
PHP Warning:  Use of undefined constant JEEDOM_BACKUP_FOLDERS - assumed 'JEEDOM_BACKUP_FOLDERS' (this will throw an Error in a future version of PHP) in /var/www/html/src/Managers/BackupManager.php on line 762
PHP Warning:  in_array() expects parameter 2 to be array, string given in /var/www/html/src/Managers/BackupManager.php on line 762
PHP Warning:  Use of undefined constant JEEDOM_BACKUP_FILES - assumed 'JEEDOM_BACKUP_FILES' (this will throw an Error in a future version of PHP) in /var/www/html/src/Managers/BackupManager.php on line 763
PHP Warning:  in_array() expects parameter 2 to be array, string given in /var/www/html/src/Managers/BackupManager.php on line 763
...Restoring folder: mobile
OK
PHP Warning:  Use of undefined constant NEXTDOM_ROOT_FOLDERS - assumed 'NEXTDOM_ROOT_FOLDERS' (this will throw an Error in a future version of PHP) in /var/www/html/src/Managers/BackupManager.php on line 760
PHP Warning:  in_array() expects parameter 2 to be array, string given in /var/www/html/src/Managers/BackupManager.php on line 760
PHP Warning:  Use of undefined constant NEXTDOM_ROOT_FILES - assumed 'NEXTDOM_ROOT_FILES' (this will throw an Error in a future version of PHP) in /var/www/html/src/Managers/BackupManager.php on line 761
PHP Warning:  in_array() expects parameter 2 to be array, string given in /var/www/html/src/Managers/BackupManager.php on line 761
PHP Warning:  Use of undefined constant JEEDOM_BACKUP_FOLDERS - assumed 'JEEDOM_BACKUP_FOLDERS' (this will throw an Error in a future version of PHP) in /var/www/html/src/Managers/BackupManager.php on line 762
PHP Warning:  in_array() expects parameter 2 to be array, string given in /var/www/html/src/Managers/BackupManager.php on line 762
PHP Warning:  Use of undefined constant JEEDOM_BACKUP_FILES - assumed 'JEEDOM_BACKUP_FILES' (this will throw an Error in a future version of PHP) in /var/www/html/src/Managers/BackupManager.php on line 763
PHP Warning:  in_array() expects parameter 2 to be array, string given in /var/www/html/src/Managers/BackupManager.php on line 763
...Restoring folder: plugins
OK
PHP Warning:  Use of undefined constant NEXTDOM_ROOT_FOLDERS - assumed 'NEXTDOM_ROOT_FOLDERS' (this will throw an Error in a future version of PHP) in /var/www/html/src/Managers/BackupManager.php on line 760
PHP Warning:  in_array() expects parameter 2 to be array, string given in /var/www/html/src/Managers/BackupManager.php on line 760
PHP Warning:  Use of undefined constant NEXTDOM_ROOT_FILES - assumed 'NEXTDOM_ROOT_FILES' (this will throw an Error in a future version of PHP) in /var/www/html/src/Managers/BackupManager.php on line 761
PHP Warning:  in_array() expects parameter 2 to be array, string given in /var/www/html/src/Managers/BackupManager.php on line 761
PHP Warning:  Use of undefined constant JEEDOM_BACKUP_FOLDERS - assumed 'JEEDOM_BACKUP_FOLDERS' (this will throw an Error in a future version of PHP) in /var/www/html/src/Managers/BackupManager.php on line 762
PHP Warning:  in_array() expects parameter 2 to be array, string given in /var/www/html/src/Managers/BackupManager.php on line 762
PHP Warning:  Use of undefined constant JEEDOM_BACKUP_FILES - assumed 'JEEDOM_BACKUP_FILES' (this will throw an Error in a future version of PHP) in /var/www/html/src/Managers/BackupManager.php on line 763
PHP Warning:  in_array() expects parameter 2 to be array, string given in /var/www/html/src/Managers/BackupManager.php on line 763
...Restoring folder: script
OK
PHP Warning:  Use of undefined constant NEXTDOM_ROOT_FOLDERS - assumed 'NEXTDOM_ROOT_FOLDERS' (this will throw an Error in a future version of PHP) in /var/www/html/src/Managers/BackupManager.php on line 760
PHP Warning:  in_array() expects parameter 2 to be array, string given in /var/www/html/src/Managers/BackupManager.php on line 760
PHP Warning:  Use of undefined constant NEXTDOM_ROOT_FILES - assumed 'NEXTDOM_ROOT_FILES' (this will throw an Error in a future version of PHP) in /var/www/html/src/Managers/BackupManager.php on line 761
PHP Warning:  in_array() expects parameter 2 to be array, string given in /var/www/html/src/Managers/BackupManager.php on line 761
PHP Warning:  Use of undefined constant JEEDOM_BACKUP_FOLDERS - assumed 'JEEDOM_BACKUP_FOLDERS' (this will throw an Error in a future version of PHP) in /var/www/html/src/Managers/BackupManager.php on line 762
PHP Warning:  in_array() expects parameter 2 to be array, string given in /var/www/html/src/Managers/BackupManager.php on line 762
PHP Warning:  Use of undefined constant JEEDOM_BACKUP_FILES - assumed 'JEEDOM_BACKUP_FILES' (this will throw an Error in a future version of PHP) in /var/www/html/src/Managers/BackupManager.php on line 763
PHP Warning:  in_array() expects parameter 2 to be array, string given in /var/www/html/src/Managers/BackupManager.php on line 763
...Restoring folder: vendor
OK
OK
migrating data...... ...Migration/Update process from --> 0.0.0
...Migration/Update process to --> 0.6.0
...Start migration process for migrate_0_0_0
ERROR 1060 (42S21) at line 36: Duplicate column name 'order'
ERROR 1060 (42S21) at line 37: Duplicate column name 'image'
ERROR 1060 (42S21) at line 38: Duplicate column name 'image'
ERROR 1060 (42S21) at line 39: Duplicate column name 'configuration'
ERROR 1060 (42S21) at line 40: Duplicate column name 'tags'
ERROR 1061 (42000) at line 42: Duplicate key name 'tags'
...Database basic update
...Done migration process for migrate_0_0_0
...Save migration process for migrate_0_0_0
...Start migration process for migrate_0_3_0
...Update theme folder
...Start moving files and folders process to /var/lib/nextdom
...Moving /var/www/html/@LongLink
...Migrate @LongLink to data/custom/@LongLink
...Migrate @LongLink to data/custom/@LongLink
...Migrate plans to data/custom/plans
...Migrate public/img/ to data/custom/plans/
...Migrate core/img/ to data/custom/plans/
...Migrate theme to data folder is done
...Done migration process for migrate_0_3_0
...Save migration process for migrate_0_3_0
...Start migration process for migrate_0_5_2
...user.function files removed
...Done migration process for migrate_0_5_2
...Save migration process for migrate_0_5_2
...Start migration process for migrate_0_6_1
sh: 1: cannot create /etc/sysctl.d/99-sysctl.conf: Permission denied
...Done migration process for migrate_0_6_1
...Save migration process for migrate_0_6_1
...Replace jeedom in database
OK
starting nextdom system......  OK
updating system configuration......  OK
checking system consistency......  OK
init values......  OK
clearing cache......  OK
restoring cache...... mv: cannot stat '/tmp/nextdom-restore-2019-12-09-15:10:31/var/cache.tar.gz': No such file or directory
OK
*************** end of restore procedure at 2019-12-09 15:11:36 ***************
*************** elapsed time 65 ***************
*************** Closing with success ***************
[ / Restore Backup Process ]

>

**Review by iWils — COMMENTED** [review]
Comme @vinceg77, des soucis ont été rencontrer lors de la restauration Jeedom (3.3.35 pour mon test) vers Nextdom:
```
[ Restore Backup Process ]
*************** starting restore procedure at 2019-12-09 23:13:35 ***************
...file used for restoration: /var/lib/nextdom/backup/backup-Jarvis-3.3.35-2019-11-08-03h33.tar.gz
OK
stopping Nextdom system......  OK
extracting backup archive......  OK
restoring plugins......  OK
restoring mysql database......  OK
importing Jeedom configuration......  OK
restoring custom data...
... ...Restoring folder: @LongLink
OK
...Restoring folder :3d
OK
...Restoring folder :custom
OK
...Restoring folder :object
OK
...Restoring folder :php
OK
...Restoring folder :plan
OK
...Restoring folder :view
OK
OK
migrating data...... ...Migration/Update process from --> 0.0.0
...Migration/Update process to --> 0.6.0
...Start migration process for migrate_0_0_0
ERROR 1060 (42S21) at line 36: Duplicate column name 'order'
ERROR 1060 (42S21) at line 37: Duplicate column name 'image'
ERROR 1060 (42S21) at line 38: Duplicate column name 'image'
ERROR 1060 (42S21) at line 39: Duplicate column name 'configuration'
ERROR 1060 (42S21) at line 40: Duplicate column name 'tags'
ERROR 1061 (42000) at line 42: Duplicate key name 'tags'
...Database basic update
...Done migration process for migrate_0_0_0
...Save migration process for migrate_0_0_0
...Start migration process for migrate_0_3_0
...Update theme folder
...Start moving files and folders process to /var/lib/nextdom
...Moving /var/www/html/config
...Migrate config to data/custom/config
...Moving /var/www/html/@LongLink
...Migrate @LongLink to data/custom/@LongLink
...Moving /var/www/html/montheme
...Migrate montheme to data/custom/montheme
...Migrate config to data/custom/config
...Migrate .htaccess to data/custom/.htaccess
...Migrate @LongLink to data/custom/@LongLink
...Migrate plans to data/custom/plans
...Migrate montheme to data/custom/montheme
...Migrate public/img/ to data/custom/plans/
...Migrate core/img/ to data/custom/plans/
...Migrate theme to data folder is done
...Done migration process for migrate_0_3_0
...Save migration process for migrate_0_3_0
...Start migration process for migrate_0_5_2
...user.function files removed
...Done migration process for migrate_0_5_2
...Save migration process for migrate_0_5_2
...Start migration process for migrate_0_6_1
sh: 1: cannot create /etc/sysctl.d/99-sysctl.conf: Permission denied
...Done migration process for migrate_0_6_1
...Save migration process for migrate_0_6_1
...Replace jeedom in database
OK
starting nextdom system......  OK
updating system configuration......  OK
checking system consistency......  OK
init values......  OK
clearing cache......  OK
restoring cache...... mv: cannot stat '/tmp/nextdom-restore-2019-12-09-23:13:36/var/cache.tar.gz': No such file or directory
OK```

En ce qui concerne la restauration de NextDom vers NextDom, je n'ai pas rencontrer d'erreur 👍

**Review by vinceg77 — APPROVED** [review]
C'est tout bon pour moi après le fix 9de1a9d, même sur un restore jeedom.
Rarement eu aussi peu d'erreurs (juste le cache à la fin !) :

> [ Restore Backup Process ]

*************** starting restore procedure at 2019-12-10 11:42:13 ***************
...file used for restoration: /var/lib/nextdom/backup/backup-MaisonChelles-3.3.39-2019-12-10-05h51.tar.gz
OK
stopping Nextdom system......  OK
extracting backup archive......  OK
restoring plugins......  OK
restoring mysql database......  OK
importing Jeedom configuration......  OK
restoring custom data...
... ...Restoring folder: @LongLink
OK
...Restoring folder :3d
OK
...Restoring folder :custom
OK
...Restoring folder :object
OK
...Restoring folder :php
OK
...Restoring folder :plan
OK
...Restoring folder :view
OK
OK
migrating data...... ...Migration/Update process from --> 0.0.0
...Migration/Update process to --> 0.6.0
...Start migration process for migrate_0_0_0
ERROR 1060 (42S21) at line 36: Duplicate column name 'order'
ERROR 1060 (42S21) at line 37: Duplicate column name 'image'
ERROR 1060 (42S21) at line 38: Duplicate column name 'image'
ERROR 1060 (42S21) at line 39: Duplicate column name 'configuration'
ERROR 1060 (42S21) at line 40: Duplicate column name 'tags'
ERROR 1061 (42000) at line 42: Duplicate key name 'tags'
...Database basic update
...Done migration process for migrate_0_0_0
...Save migration process for migrate_0_0_0
...Start migration process for migrate_0_3_0
...Update theme folder
...Start moving files and folders process to /var/lib/nextdom
...Moving /var/www/html/@LongLink
...Migrate @LongLink to data/custom/@LongLink
...Migrate @LongLink to data/custom/@LongLink
...Migrate plans to data/custom/plans
...Migrate .htaccess to data/custom/.htaccess
...Migrate public/img/ to data/custom/plans/
...Migrate core/img/ to data/custom/plans/
...Migrate theme to data folder is done
...Done migration process for migrate_0_3_0
...Save migration process for migrate_0_3_0
...Start migration process for migrate_0_5_2
...user.function files removed
...Done migration process for migrate_0_5_2
...Save migration process for migrate_0_5_2
...Start migration process for migrate_0_6_1
sh: 1: cannot create /etc/sysctl.d/99-sysctl.conf: Permission denied
...Done migration process for migrate_0_6_1
...Save migration process for migrate_0_6_1
...Replace jeedom in database
OK
starting nextdom system......  OK
updating system configuration......  OK
checking system consistency......  OK
init values......  OK
clearing cache......  OK
restoring cache...... mv: cannot stat '/tmp/nextdom-restore-2019-12-10-11:42:14/var/cache.tar.gz': No such file or directory
OK
*************** end of restore procedure at 2019-12-10 11:43:11 ***************
*************** elapsed time 58 ***************
*************** Closing with success ***************
[ / Restore Backup Process ]

>

**Comment by slobberbone** [comment]
En fait ce n'est aps une bonne idée cette PR

**Comment by vinceg77** [comment]
:)

**Pull request closed without merging**
