### PR TITLE
Restore/Backup/migration

### PR DESCRIPTION
**Pull request by slobberbone**
This feature allow to manage migration process in NextDom. This is linked to backup and restore process.

# Migration #
This process is called on :
- Import backup action
- Upgrade NextDom from .deb package
- Upgrade NextDom from github

The migration process is : 

1. Check previous version (0.0.0 in import mode)
2. Check current version
3. Search migration function for each version
4. Execute migration for each version between previous and current version

0.0.0 Migration content : 
- [x] Migrate some table (old migration stuff) see migrate_0_0_0.sql file
- [x] Enable interactDefinition entries

0.3.0 Migration content : 
- [x] Move all root custom folders and files to data/custom
- [x] Apply perms for these folders and files
- [x] Update fields in plan and plan3d table for all root custom folder and file to data/custom
- [x] Update user.function.class.php

# Backup #
The backup process was reviewed, now we backup also : 
- [x] Data directory (config + custom)
- [x] Backup file contains NextDom version instead of Jeedom
- [x] Check free space to create backup (400Mo min)

# Restore #
The restore process was reviewed too : 
- [x] Data directory (config + custom)
- [x] Check free space to extract the backup archive

# Tests and check # 

1.Empty
- [x] create empty backup in 0.3.0
- [x] restore empty backup in 0.3.0

2.Existing < 0.2.0
- [x] import your backup in 0.3.0
- [x] create backup in 0.3.0
- [x] restore backup in 0.3.0

3.Existing = 0.2.0
- [x] upgrade to 0.3.0
- [x] create backup in 0.3.0
- [x] restore backup in 0.3.0

### CODE REVIEW

**Comment by Esso1-jeedom** [comment]
pour moi ca fonctionne

**Comment by slobberbone** [comment]
> pour moi ca fonctionne

@Esso1-jeedom tu peux donner le détail de ce que tu as fais comme actions stp ?

**Review by ColonelMoutarde — DISMISSED** [review]
Il ne faut pas utiliser dirname(__file__) il faut utiliser __DIR__
tu vois ça où ? @ColonelMoutarde

**Comment by ColonelMoutarde** [comment]
> Il ne faut pas utiliser dirname(**file**) il faut utiliser **`__DIR__`**
> tu vois ça où ? @ColonelMoutarde

MigrationHelper.php ligne 332

` $fromString = 'require_once dirname(__FILE__) . \'/../../core/php/core.inc.php\';';`

https://blog.pascal-martin.fr/post/php-5.3-constante-magique-__dir__/

**Comment by slobberbone** [comment]
> > Il ne faut pas utiliser dirname(**file**) il faut utiliser **`__DIR__`**
> > tu vois ça où ? @ColonelMoutarde
> 
> MigrationHelper.php ligne 332
> 
> ` $fromString = 'require_once dirname(__FILE__) . \'/../../core/php/core.inc.php\';';`
> 
> https://blog.pascal-martin.fr/post/php-5.3-constante-magique-__dir__/

@ColonelMoutarde oui mais là je remplace ce code venant de jeedom donc ca n'a pas d'incidence et il faut surtout pas le corriger ;)

ok :)

**Review by Sylvaner — APPROVED** [review]

**Review by byackee — APPROVED** [review]

**Review by Esso1-jeedom — APPROVED** [review]

**Review by ColonelMoutarde — APPROVED** [review]

**Pull request merged**
