### PR TITLE
Refactoring of install procedure

### PR DESCRIPTION
**Pull request by psycofdj**
### install procedure

* delete all `.htaccess`, equivalent configuration sent to apache `nextdom-common.conf`
* factorize most of `nextdom` and `nextdom-ssl` vhost configuration be fining a new file `nextdom-common` included by both of them
* removed `nextdom-security.conf`, its directives are now in `nextdom-common.conf` which defines configuration only for nextdom instead of all system
* rewrite `install/postinst` script for better output and error handling
  * php ini directives are no more edited on system but instead are given by `nextdom-common.conf`
* rewrite `scripts/gen_assets.sh` for better readability 
* rewrite `scripts/gen_composer_npm.sh` for better readability 

### project tree structure

* makes external paths more configurable by adding configurations keys to `common.config.php`
* `theme.css`, which is writable from the UI, is now located in `NEXTDOM_DATA`
* use `NEXTDOM_DATA` instead of `NEXTDOM_ROOT/var` when possible
* remove `chmod 777` and `chown www-data` from almost all source directories
  * it remains *plugins*, *profiles*, *themes*, *plan* and *plan3d*. The last four could be easily moved to data directory with a little migration handling

### cleaning

* removes unnecessary execute permission to most source files
* removes unused files such as `install/apache_default` or `install/apache_security`
* refactoring of file upload handling: adds `Utils::readUploadedFile` function and use it in ajax files

### backup/restore
* adds new composer dependency: `splitbrain/php-archive`
  * allows to create and read backup archive that have a different directory layout than source tree
* complete rewrite of `install/backup.php` and `install/restore.php`. All procedure is now handled by `BackupManager` class
* complete rewrite of `install/consistency.php` All procedure is now handled by `ConsistencyManager` class

### minor fixes and improvments
* ensure php `7.2` compatibility by removing last calls to `object` class
* fix curious call to `CronManager::clean` in `NextDomHelper`
* fix warning about invalid integer in `SystemHelper::getUptime`
* fix warning about invalid integer in `InteractQueryManager::recognize`
* fix unknown method due to shadowed variable in `CronManager::clean`
* fix type warning in `\Entity\Cron::preSave()`
* fix bug scenario template upload (missing token)
* fix warning in `nextdom.ajax.php` when handling file without extension
* adds some helper functions:
  * `SystemHelper::vsystem`: run `system` command and takes printf-like arguments
  * `Utils::parseArgs`
  * `Utils::array_key_default`: get key from array, or default

### Tests

* unit tests:
  * [x] execute unit tests
* Install procedure:
  * [x] install nextfrom from scratch
  * [x] validate cron and watchdog execution
  * [x] update migration from nextdom:stable to this branch
  * [x] validate install in docker environment
* Backup & Restore tests
  * [x] import a jeedom backup archive in fresh nextdom install
  * [x] generate a backup archive
  * [x] import a nextdom backup archive
  * [x] upload a backup archive in UI
  * [x] restore from uploaded backup archive
  * [x] validate backup file rotation (MaxDays and MaxSize)
  * [x] validate some retored plugins: openzwave, broadlink, mode, sonybravia, virtual, weather ...
* Tests about directory change
  * [x] change theme
  * [x] upload a new profile picture
  * [x] test update procedures (core/plugin)
* Tests about cleaning
  * [x] upload backup
  * [x] upload custom `js` and `css` file
  * [x] upload a plan
  * [x] ~~upload a plan3d~~ 
    * feature disabled in nextdom
  * [x] upload a profile
  * [x] upload a scenario template
  * [x] ~~test `preUploadFile` in `update.ajax.php` if possible~~
    * feature not working on nextdom: `views/modals/update.add.html.twig:52:`, bad token
  * [x] ~~test slave upload and backup upload from `proApi.ajax.php` if possible~~
    * honestly very difficult to test for a small change
    * I doubt that this feature is very commonly used
    * a code review should be enough

### CODE REVIEW

**Comment by psycofdj** [comment]
Can someone help me with the failing travis test ? I have no clue...

**Comment by slobberbone** [comment]
@psycofdj Pour Travis : 
` 0.21s$ ./scripts/gen_global.sh
Installation de sass
sudo: npm: command not found
The command "./scripts/gen_global.sh" failed and exited with 1 during .`
as-tu modifié ce script ?

**Comment by psycofdj** [comment]
@slobberbone non justement, j’espérai que l'erreur serait coté travis
je vais regarder

**Comment by Sylvaner** [comment]
Pour tester
```
git fetch origin pull/1021/head:develop
git checkout develop
```

**Comment by Sylvaner** [comment]
J'ai fait une installation complète. Niquelle
A la restauration d'un backup : 
```
restoring cache...oK
restoring plugins...PHP Warning:  rename(): The first argument to copy() function cannot be a directory in /usr/share/nextdom/src/Managers/BackupManager.php on line 678
PHP Warning:  rename(/tmp/nextdom-restore-2019-04-21-08:57:17/plugins/RTSP,/usr/share/nextdom/plugins/RTSP): Invalid cross-device link in /usr/share/nextdom/src/Managers/BackupManager.php on line 678
PHP Warning:  rename(): The first argument to copy() function cannot be a directory in /usr/share/nextdom/src/Managers/BackupManager.php on line 678
PHP Warning:  rename(/tmp/nextdom-restore-2019-04-21-08:57:17/plugins/blea,/usr/share/nextdom/plugins/blea): Invalid cross-device link in /usr/share/nextdom/src/Managers/BackupManager.php on line 678
PHP Warning:  rename(): The first argument to copy() function cannot be a directory in /usr/share/nextdom/src/Managers/BackupManager.php on line 678
PHP Warning:  rename(/tmp/nextdom-restore-2019-04-21-08:57:17/plugins/lametric,/usr/share/nextdom/plugins/lametric): Invalid cross-device link in /usr/share/nextdom/src/Managers/BackupManager.php on line 678
PHP Warning:  rename(): The first argument to copy() function cannot be a directory in /usr/share/nextdom/src/Managers/BackupManager.php on line 678
PHP Warning:  rename(/tmp/nextdom-restore-2019-04-21-08:57:17/plugins/openzwave,/usr/share/nextdom/plugins/openzwave): Invalid cross-device link in /usr/share/nextdom/src/Managers/BackupManager.php on line 678
PHP Warning:  rename(): The first argument to copy() function cannot be a directory in /usr/share/nextdom/src/Managers/BackupManager.php on line 678
PHP Warning:  rename(/tmp/nextdom-restore-2019-04-21-08:57:17/plugins/script,/usr/share/nextdom/plugins/script): Invalid cross-device link in /usr/share/nextdom/src/Managers/BackupManager.php on line 678
PHP Warning:  rename(): The first argument to copy() function cannot be a directory in /usr/share/nextdom/src/Managers/BackupManager.php on line 678
PHP Warning:  rename(/tmp/nextdom-restore-2019-04-21-08:57:17/plugins/virtual,/usr/share/nextdom/plugins/virtual): Invalid cross-device link in /usr/share/nextdom/src/Managers/BackupManager.php on line 678
PHP Warning:  rename(): The first argument to copy() function cannot be a directory in /usr/share/nextdom/src/Managers/BackupManager.php on line 678
PHP Warning:  rename(/tmp/nextdom-restore-2019-04-21-08:57:17/plugins/widget,/usr/share/nextdom/plugins/widget): Invalid cross-device link in /usr/share/nextdom/src/Managers/BackupManager.php on line 678
PHP Warning:  rename(): The first argument to copy() function cannot be a directory in /usr/share/nextdom/src/Managers/BackupManager.php on line 678
PHP Warning:  rename(/tmp/nextdom-restore-2019-04-21-08:57:17/plugins/wifilightV2,/usr/share/nextdom/plugins/wifilightV2): Invalid cross-device link in /usr/share/nextdom/src/Managers/BackupManager.php on line 678
PHP Warning:  rename(): The first argument to copy() function cannot be a directory in /usr/share/nextdom/src/Managers/BackupManager.php on line 678
PHP Warning:  rename(/tmp/nextdom-restore-2019-04-21-08:57:17/plugins/xiaomihome,/usr/share/nextdom/plugins/xiaomihome): Invalid cross-device link in /usr/share/nextdom/src/Managers/BackupManager.php on line 678
oK
```

**Review by Sylvaner — APPROVED** [review]

**Review by ColonelMoutarde — APPROVED** [review]

**Comment by Esso1-jeedom** [comment]
il y a des pb avec les backup.  pour le telechargement , et la création qui supprime et ne laisse que 1 backup

**Comment by psycofdj** [comment]
@Esso1-jeedom tu es sûr que ce n'est pas le mécanisme de rotation des backups qui entre en action ?
le fait qu'il ne garde les backups sur 3 jours et sur un maximum de 500Mo au total ?

**Comment by psycofdj** [comment]
@Esso1-jeedom problème réglé.
Pour la petite histoire: tout le code était OK mais j'avais laissé une ligne qui limitait la taille total des backup à 32Mo pour tester la condition de rotation.... j'ai oublié de l'enlever ^^

**Review by Esso1-jeedom — APPROVED** [review]

**Pull request merged**
